name: Trigger Hidden Workflow

on:
  push:
    branches: [ main ] # 当 main 分支有新的 push 时触发
  pull_request:
    branches: [ main ] # 当向 main 分支发起 pull request 时触发
  workflow_dispatch: # 允许手动触发此工作流
    inputs:
      KERNEL_SUFFIX:
        description: '内核名称修改(可改中文和emoji)'
        required: true
        default: '-android15-8-g013ec21bba94-abogki383916444-4k'
      KERNEL_TIME:
       description: "内核构建日期更改(默认为原厂)"
       required: true
       default: 'Tue Dec 17 23:36:49 UTC 2024'
      enable_feature_x:
       description: "是否启用kpm"
       required: false
       default: false
       type: boolean
      enable_feature_y:
       description: "是否启用lz4kd"
       required: false
       default: false
       type: boolean
      enable_feature_z:
       description: "是否开启真GKI风驰"
       required: false
       default: false
       type: boolean

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Trigger private workflow via repository_dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ steps.generate_token.outputs.token }} # 使用 GitHub App 生成的 token
          repository: Plan2241/my-hidden-workflows # 您的私有仓库
          event-type: run_hidden_workflow # 自定义事件名称，私有工作流将监听此事件
          client-payload: '{"ref": "${{ github.event.inputs.ref || github.ref }}", "sha": "${{ github.event.inputs.sha || github.sha }}", "public_repo": "${{ github.repository }}", "KERNEL_SUFFIX": "${{ github.event.inputs.KERNEL_SUFFIX }}", "KERNEL_TIME": "${{ github.event.inputs.KERNEL_TIME }}", "enable_feature_x": "${{ github.event.inputs.enable_feature_x }}", "enable_feature_y": "${{ github.event.inputs.enable_feature_y }}", "enable_feature_z": "${{ github.event.inputs.enable_feature_z }}"}'

